# Generated by Django 2.1 on 2018-09-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180925_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
